version: '3'
services:
  alten-shop-front:
    image: alexv31/alten-shop:front
    restart: always
    depends_on:
      - alten-shop-api
    networks:
      - alten-shop-network
    ports:
      - "80:80"


  alten-shop-api:
    image: alexv31/alten-shop:api
    restart: always
    depends_on:
      - alten-shop-db
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MYSQL_HOST=alten-shop-db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=alten-shop-root-password
      - MYSQL_DATABASE=alten-shop
    networks:
      - alten-shop-network
    ports:
      - "3000:3000"


  alten-shop-db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=alten-shop-root-password
      - MYSQL_DATABASE=alten-shop
    networks:
      - alten-shop-network
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  alten-shop-network:
    driver: bridge